import type { AlbumItem } from '../model/types';

export const MOCK_ALBUM_ITEMS: AlbumItem[] = [
  {
    id: 'album-1',
    title: '어린 시절 고향',
    elderName: '박영호',
    date: '1975.04.',
    location: '구지면',
    year: '1975년',
    memo: '가족끼리 나들이에 갔던 날이에요',
    photos: ['photo-1-1', 'photo-1-2', 'photo-1-3', 'photo-1-4', 'photo-1-5'],
    senderRelation: '딸',
    tags: ['아버지', '어머니', '할머니'],
    conversation: {
      question: '이 사진, 기억나세요?',
      askedRelativeTime: '3일전',
      answer: {
        authorName: '박영호 님',
        relativeTime: '2일전',
        time: '오후 3:20',
        tags: ['그리움', '행복'],
        quote: '그 냇가 참 좋았지... 친구들이랑 물고기 잡던 게 아직도 생생해.',
        audioDuration: '0:02',
      },
    },
  },
  {
    id: 'album-2',
    title: '첫 자전거를 배운 날',
    elderName: '박영호',
    date: '1978.06.',
    location: '마당',
    year: '1978년',
    memo: '아버지가 뒤에서 잡아주셨던 자전거예요',
    photos: ['photo-2-1', 'photo-2-2'],
    senderRelation: '아들',
    tags: ['아버지'],
    conversation: {
      question: '누가 자전거 타는 법을 가르쳐주셨어요?',
      askedRelativeTime: '5일전',
    },
  },
  {
    id: 'album-3',
    title: '결혼기념일 여행',
    elderName: '박영호',
    date: '1990.05.',
    location: '설악산',
    year: '1990년',
    conversation: {
      question: '신혼여행은 어디로 가셨어요?',
      askedRelativeTime: '1주전',
    },
  },
  {
    id: 'album-4',
    title: '첫 손주 돌잔치',
    elderName: '박영호',
    date: '2005.11.',
    location: '부산',
    year: '2005년',
    memo: '첫 손주를 안았던 날, 정말 기뻤어요',
    photos: ['photo-4-1'],
    senderRelation: '딸',
    tags: ['손주'],
    conversation: {
      question: '손주를 처음 안았을 때 기분이 어떠셨어요?',
      askedRelativeTime: '4일전',
      answer: {
        authorName: '박영호 님',
        relativeTime: '3일전',
        time: '오전 10:05',
        tags: ['설렘', '뿌듯'],
        quote: '말로는 다 못 하지... 그저 고맙고 예뻤어.',
        audioDuration: '0:05',
      },
    },
  },
  {
    id: 'album-5',
    title: '환갑잔치',
    elderName: '박영호',
    date: '1998.03.',
    location: '대구',
    year: '1998년',
  },
  {
    id: 'album-6',
    title: '시집오던 날',
    elderName: '김순자',
    date: '1965.10.',
    location: '안동',
    year: '1965년',
    memo: '가마 타고 시댁으로 향하던 날이에요',
    photos: ['photo-6-1', 'photo-6-2', 'photo-6-3'],
    conversation: {
      question: '시집오시던 날 기분이 어떠셨어요?',
      askedRelativeTime: '2일전',
    },
  },
  {
    id: 'album-7',
    title: '첫 딸이 태어난 날',
    elderName: '김순자',
    date: '1970.02.',
    location: '서울',
    year: '1970년',
    memo: '첫 아이를 품에 안았던 순간이에요',
    conversation: {
      question: '이 사진, 기억나세요?',
      askedRelativeTime: '6일전',
      answer: {
        authorName: '김순자 님',
        relativeTime: '5일전',
        time: '오후 1:40',
        tags: ['행복'],
        quote: '세상을 다 가진 것 같았지, 그때는.',
        audioDuration: '0:03',
      },
    },
  },
  {
    id: 'album-8',
    title: '텃밭 가꾸던 시절',
    elderName: '이순자',
    date: '1995.07.',
    location: '시골집',
  },
];
